### ISSUE TITLE
Can't update nested field

### ISSUE THREAD

**Issue by ColtonIdle** [DroidsOnRoids/bitrise-step-update-jira-issue-field#4]
I was able to get the step to work when updating a field like `summary`, but I want to update the `name` of `status` field.

Here’s a look into the metadata when I pull it down using the jira api via curl

```
 {  
   "id":"123456",
   "self":"myissueUrl",
   "key":"XY-123",
   "fields":{  
      "issuetype":{  },
      "parent":{  },
      "timespent":null,
      "status":{  
         "self":"myIssueUrl",
         "description":"my description",
         "iconUrl":"icon.png",
         "name":"I WANT TO UPDATE THIS FIELD RIGHT HERE",
         "id":"1",
         "statusCategory":{  }
      },      "components":[  ],
      "timeoriginalestimate":null,
      "description":"Desctip of the issue",
      "summary":"Summary of the issue",
      "creator":{  },
      "subtasks":[  ],
      "reporter":{  },
      "duedate":null,
      "progress":{  },
      "votes":{  },
      "comment":{  },
      "worklog":{  }
   }
}
```

I also submitted it as a question here just in case there is actually a way to do it via some delimiter that I'm missing.

https://discuss.bitrise.io/t/how-to-update-a-nested-field-using-update-jira-issues-field-step/4353

**Comment by koral--** [comment]
I'll check that ASAP.

**Comment by ColtonIdle** [comment]
@koral--  is there any other information I can get for you that would help?

**Comment by koral--** [comment]
Could paste part of the response to `https://<jira instance URL>/rest/api/2/issue/<issue key>/editmeta` corresponding to `status` field?

**Comment by ColtonIdle** [comment]
@koral-- 

Here's what I get when I make that call:

```
{  
   "fields":{  
      "summary":{  },
      "issuetype":{  },
      "components":{  },
      "description":{  },
      "customfield_10021":{  },
      "fixVersions":{  },
      "priority":{  },
      "customfield_11202":{  },
      "customfield_10004":{  },
      "labels":{  },
      "customfield_10006":{  },
      "customfield_10007":{  },
      "attachment":{  },
      "customfield_11704":{  },
      "issuelinks":{  },
      "comment":{  },
      "assignee":{  }
   }
}
```

I did a search for `status` in the entire json response, but there was nothing!

Does this mean it can't be edited? If so, that's very very weird.

EDIT: Really old but maybe helpful? https://community.atlassian.com/t5/Jira-questions/JIRA-How-to-change-issue-status-via-rest/qaq-p/528133

EDIT 2: Maybe I'm not looking to change the status, but I'm looking to make a `transition`?
Last comment from the above link

```
I would first get available transitions:

https://docs.atlassian.com/jira/REST/server/#api/2/issue-getTransitions

Then do a post:
https://docs.atlassian.com/jira/REST/server/#api/2/issue-doTransition
```

**Comment by koral--** [comment]
Right.
Only fields listed in `GET editmeta` response can be edited in terms of JIRA.

OTOH `status` can be changed implicitly using transition. During the transition some fields can be updated like `asignee` and update of some others may be required in particular transitions e.g. if issue is being closed then `resolution` must be set to either "Fixed" or "Cannot reproduce" etc.

It looks like out of the scope of this step. But I can try to create a new step let's say "Transition JIRA issue" with inputs for transition id and fields to be updated.
Do you have any preference how should it look like?

**Comment by ColtonIdle** [comment]
@koral-- I would love to help you debug/develop as best I can. I am still trying (and failing) to get bitrise cli running on my local or else I feel like I would be a bigger help.

My use case is that after I make a build, I have a release notes section with a comma separated list of Jira issues, that I'd love to move from their current status (usually "In development") to something like "Ready for testing".

**Comment by koral--** [comment]
OK, so (apart from JIRA credentials and issue IDs) there must be required input for transition id and additionally one more optional for field(s) update.
On JIRA instance which I use there is a requirement to specify a `resolution` if is issue is transitioned into `In test`.
You can check for required fields using `GET https://<jira instance URL>/rest/api/2/issue/<issue Id or Key>/transitions?expand=transitions.fields`,

Fields structure looks like that:
```
{
        "assignee": {
          "name": "bob"
        },
        "resolution": {
          "name": "Fixed"
        }
}
```
It seems that they can be specified directly as that JSON in input field.

Do you have any better idea?

**Comment by koral--** [comment]
Closing this due inactivity. May be reopened if needed.

**Comment by anniewey** [comment]
How do I update JIRA issue's field based on the issue key tagged in commit message? Is this possible?

Eg: 
Commit message: `PRJ-001, PRJ-234 Add new feature`
Upon CI build successful, update all JIRA issues from the commit (`PRJ-001`, `PRJ-234`) from `In Progress` to `Done`

**Comment by koral--** [comment]
> from In Progress to Done

In JIRA terminology such change is not a field update but transition.
This step currently does not support transitions.

It may be added in the future, but for now there is even no idea how to design inputs for that, do you have some insights?

**Comment by anniewey** [comment]
Ah, sorry about that wrong terminology. So if I would like to update fields like `fixVersions` for all the tasks in the commit message, could it be done in this step?

I'm not sure I can be of any help since I'm still new on Bitrise. But what I mean is similar to `JIRA Comments` step (Comments are added to JIRA cases based on the commits message to determine which tasks should be commented). 

Instead of adding comment, I would like to make a transition by inputting the transition id in the step. In this case, every tasks mentioned in the commit will change its transition to the inputted transition id.

Perhaps combining this step and `JIRA Comments`? Input variables could be:
1. JIRA credentials
2. JIRA project details (project prefix/domain/etc - from `JIRA Comments` step) *if using search task method instead of inputting `list of issue ids/key`
3. Field key
4. Field value
5. Make transition (true/false)
    -> if true 
    6. Transition id (can the same transition id apply to different issues?)

Not sure if this proposal is applicable as I have never create a step nor using JIRA api. Just my idea.
