### ISSUE TITLE
Assignee data was not an object

### ISSUE THREAD

**Issue by Shebella** [DroidsOnRoids/bitrise-step-update-jira-issue-field#8]
Hi @koral-- 
When I try to run the Bitrise step of Update JIRA issues field
I got this error message

Configs:
 - JiraUsername: [REDACTED]
 - JiraPassword (hidden): *****
 - JiraInstanceURL: [REDACTED]
 - IssueIdOrKeyList: [RFMA-1234]
 - FieldKey: assignee
 - FieldValue: {"name" : "rubio"}

Updating issue RFMA-1234
JIRA API response status: 400 Bad Request
JIRA API response: {"errorMessages":[],"errors":{"assignee":"data was not an object"}}
Could not update issue, error: JIRA API request failed

May I know what should be the correct format in order to update the assignee field？
Thanks for your support！
Rubio

**Comment by koral--** [comment]
Thanks for the report, I'll check that.

**Comment by koral--** [comment]
I couldn't find a direct answer in official docs. However it seems that the API endpoint used by this step allows to pass only plain strings, numbers and empty values.

More complex entities like user cannot be passed that way. There are the separate endpoints for each of them. In case of  assignee: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-assignee-put
