### ISSUE TITLE
Fix versions update fails

### ISSUE THREAD

**Issue by RoyPayKey** [DroidsOnRoids/bitrise-step-update-jira-issue-field#9]
Hi,

on readme it says fix version is part of the fields you can update however, 
when using fixVersions key it expects an array but is sent as string which makes the step failing.

log from build:
JIRA API response status: 400 Bad Request
JIRA API response: {"errorMessages":[],"errors":{"fixVersions":"data was not an array"}}
Could not update issue, error: JIRA API request failed

**Comment by koral--** [comment]
This step, or more precisely the endpoint in Jira REST API used by it, allows only to pass only plain data types like a single number or text. See: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-assignee-put
Note that you have a field called 'Fix version**s**' (plural) on your Jira which expects an array of versions. While readme says about the single "Fix version".

I have no plans to add support for more complex data types in this step. However, PRs are welcome.

**Comment by RoyPayKey** [comment]
Okay thank you, 
Just as a side note, there's no fix version field in jira issues (at least not anymore) 
the only field regarding fix version is fixVersions which takes an array.

**Comment by koral--** [comment]
Thanks for the info, will check that and update readme.
